# -*- coding: utf-8 -*-
"""ensemble model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ay4uGGN7zuV5_XmYJzUHsGfVcfxeb7rc
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'kermany2018:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F17839%2F23942%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240512%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240512T132629Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D54ce6c5a070932a44f97f1839db70741ea19d29c25dea1020a85bf47e741c2d304d4d1951f78845b33db0434e2212225bdf877c835a214615789e457165cb7cf2cefe0cb5a8d7563fe1badd88c845aedb8095088c4aa3c94b7670ccacca2bf4978ffc1e1cb1933dcc47f703c0f1d17850011921f0d8365ae6419a3fd04d684acd842f369cb457541d3ca5c9f96a46fac706781f4ef7e9a52cf4a0ff6b4d02547f23abbbb164009c9ec5deab83b149afe1c44c0e15e69a1a12f17a20dee90cfad2e8ab60b2daf901a48b9dce9555d335009ae8b73d906119554423abd73ba211a1942f98d09813a27f0674e5b8e13bbed45a2fea14b091965ce7f83c5a50e7ce0'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten,Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.models import Sequential
from tensorflow.keras.applications import InceptionResNetV2
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image
import cv2
import os
import glob
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16
from keras.layers import Activation,Dense, Dropout, Flatten, Conv2D, ReLU
from keras.models import Model
from keras.applications.inception_v3 import InceptionV3
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from keras.optimizers import SGD, Adam
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, precision_recall_curve, f1_score
from tensorflow.keras.utils import plot_model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from sklearn.model_selection import train_test_split
import itertools
# re-size all the images to this
IMAGE_SIZE = [224, 224]

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, MaxPooling2D, Dropout, Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

total = 83484

count_cnv = 37205
count_dme = 11348
count_drusen = 8616
count_normal = 26315

cnv_weight = (1/count_cnv) * (total/4)
dme_weight = (1/count_dme) * (total/4)
drusen_weight = (1/count_drusen) * (total/4)
norm_weight = (1/count_normal) * (total/4)

class_weight = {0 : cnv_weight, 1: dme_weight, 2 : drusen_weight, 3: norm_weight}
print(class_weight)


labels = ['CNV', 'DME', 'DRUSEN', 'NORMAL']

training_data_processor = ImageDataGenerator(rescale=1./255,fill_mode='nearest')

test_data_processor = ImageDataGenerator(rescale = 1./255,fill_mode='nearest')

train_path = '/kaggle/input/kermany2018/OCT2017 /train'
test_path = '/kaggle/input/kermany2018/OCT2017 /test'
val_path = '/kaggle/input/kermany2018/OCT2017 /val'

# Load data into Python
training_data = training_data_processor.flow_from_directory(
    train_path,
    target_size = (224, 224),
    batch_size = 32,
    class_mode = 'categorical')

testing_data = test_data_processor.flow_from_directory(
    test_path,
    target_size = (224 ,224),
    batch_size = 32,
    class_mode = 'categorical',
    shuffle = False)

keras_model1 = tf.keras.models.load_model('vgg19_model.h5', compile=False)
keras_model1._name = 'model1'
keras_model2 = tf.keras.models.load_model('vgg16_model.h5', compile=False)
keras_model2._name = 'model2'
keras_model3 = tf.keras.models.load_model('inc_model.h5', compile=False)
keras_model3._name = 'model3'

models = [keras_model1,
          keras_model2,
          keras_model3,
          ]
model_input = tf.keras.Input(shape=(224,224, 3))
model_outputs = [model(model_input) for model in models]
ensemble_output = tf.keras.layers.Average()(model_outputs)
ensemble_model = tf.keras.Model(inputs = model_input,
                                outputs = ensemble_output,
                                name='ensemble')
ensemble_model.summary()

ensemble_model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

opt = Adam(learning_rate=0.0001)
early_stop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2, verbose=1, min_lr=1e-7)

history4 = ensemble_model.fit(
    training_data,
    steps_per_epoch=327,
    epochs=15,
    validation_data=testing_data,
    callbacks=[early_stop, reduce_lr])

ensemble_model.save('ensemble_model.h5')

test3_loss, test3_accuracy = ensemble_model.evaluate(testing_data)

predictions3 = ensemble_model.predict(testing_data)

y_pred3 = np.argmax(predictions3, axis=1)
y_true3 = testing_data.classes

labels = {value: key for key, value in training_data.class_indices.items()}

print("Label Mappings for classes present in the training and validation datasets\n")
for key, value in labels.items():
    print(f"{key} : {value}")

from sklearn.metrics import confusion_matrix, classification_report
cf_mtx3 = confusion_matrix(y_true3, y_pred3)

print(classification_report(y_true3, y_pred3, target_names=labels.values()))
print("classification report for ensemble model")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import seaborn as sns

ax= plt.subplot()
sns.heatmap(cf_mtx3, annot=True,cmap='Blues',ax=ax,fmt='g')
ax.set_xlabel('Predicted labels');ax.set_ylabel('True labels');
ax.set_title('Confusion Matrix');
ax.xaxis.set_ticklabels(['CNV', 'DME','DRUSEN','NORMAL']); ax.yaxis.set_ticklabels(['CNV', 'DME','DRUSEN','NORMAL']);
print("Confusion matrix for ensemble model")

plt.plot(history4.history['loss'], label='train loss')
plt.plot(history4.history['val_loss'], label='val loss')
plt.legend()
plt.show()
plt.savefig('LossVal_loss')

# plot the accuracy
plt.plot(history4.history['accuracy'], label='train acc')
plt.plot(history4.history['val_accuracy'], label='val acc')
plt.legend()
plt.show()
plt.savefig('AccVal_acc')





